version: "2"
services:
  suma:
    build: ./suma
    ports: ["5001:5000"]
  name:
    build: ./name
    ports: ["5002:5000"]
  app:
    build: ./app
    ports: ["5003:5000"]
    depends_on:
      - name
      - suma
